export const CLIENTS_LOGOS = [
    { title: "After hour", img: "/clientsLogo/AfterhourLogo.png" },
    { title: "Agility", img: "/clientsLogo/AgilityLogo.png" },
    { title: "Ancol Mansion", img: "/clientsLogo/AncolMansionLogo.png" },
    { title: "Asahimas Flat Glass", img: "/clientsLogo/AsahimasFlatGlassLogo.png" },
    { title: "Bank Bumi Arta", img: "/clientsLogo/BankBumiArtaLogo.png" },
    { title: "Bank Dagang Negara", img: "/clientsLogo/BankDagangNegaraLogo.png" },
    { title: "Cathay Pasific", img: "/clientsLogo/CathayPasificLogo.png" },
    { title: "Clay Hotel", img: "/clientsLogo/ClayHotelLogo.png" },
    { title: "Gading Resort", img: "/clientsLogo/GadingResortLogo.png" },
    { title: "Golden Rama", img: "/clientsLogo/GoldenRamaLogo.png" },
    { title: "Honda", img: "/clientsLogo/HondaLogo.png" },
    { title: "Indonesia Stock Exchange", img: "/clientsLogo/idxLogo.png" },
    { title: "Inaco", img: "/clientsLogo/InacoLogo.png" },
    { title: "Juanda Apartement", img: "/clientsLogo/JuandaApartementLogo.png" },
    { title: "Lumire", img: "/clientsLogo/LumireLogo.png" },
    { title: "Maven Hotel", img: "/clientsLogo/MavenHotelLogo.png" },
    { title: "Mall of Indonesia", img: "/clientsLogo/MOILogo.png" },
    { title: "PT. Obsidian Stainless Steel", img: "/clientsLogo/ObsidianStainlessSteelLogo.png" },
    { title: "Panalpina", img: "/clientsLogo/PanalpinaLogo.png" },
    { title: "Saint Theresia", img: "/clientsLogo/SaintTheresiaLogo.png" },
    { title: "Sate Senayan", img: "/clientsLogo/SateSenayanLogo.png" },
    { title: "Schenker", img: "/clientsLogo/SchenkerLogo.png" },
    { title: "Siloam Hospital", img: "/clientsLogo/SiloamHospitalLogo.png" },
    { title: "Smailing Tour", img: "/clientsLogo/SmailingTourLogo.png" },
    { title: "Taipei Fubon Bank", img: "/clientsLogo/TaipeiFubonBank.png" },
    { title: "PT. Virtue Dragon Nickel Industry", img: "/clientsLogo/VDNILogo.png" },
    { title: "Wisma77", img: "/clientsLogo/Wisma77Logo.png" },
]
